MODEL:
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_backbone"
  WEIGHTS: http://dl.fbaipublicfiles.com/cutler/checkpoints/dino_RN50_pretrain_d2_format.pkl #"detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  RESNETS:
    DEPTH: 50
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    # NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 1, 1]  # not used
DATASETS:
  TRAIN: ("unsam_sa1b_train",)
  TEST: ("unsam_sa1b_val",)
  SELF_TRAIN: false
  SELF_TRAIN_NUMBER: 1
  SELF_TRAIN_THRESH_LOW: 0.0
  SELF_TRAIN_THRESH_HIGH: 1.0
SOLVER:
  DROPLOSS_IOU_THRESH: 0.01
  USE_DROP_LOSSES: false
  IMS_PER_BATCH: 4
  BASE_LR: 1e-6 #5e-5
  STEPS: (177776, 192592) #(327778, 355092)
  MAX_ITER: 200000 #368750
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
INPUT:
  IMAGE_SIZE: 1024
  MIN_SCALE: 1.0 #0.1
  MAX_SCALE: 1.0 #2.0
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TEST: 2048
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "sam_instance_tsv"
TEST:
  EVAL_PERIOD: 0 #5000
  DETECTIONS_PER_IMAGE: 1000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 1
VERSION: 2
